"""latest db changes

Revision ID: 257e30585ca9
Revises: 01e28756f35c
Create Date: 2025-11-06 14:21:43.968253

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "257e30585ca9"
down_revision: Union[str, Sequence[str], None] = "01e28756f35c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
