"""tag change again

Revision ID: 722b8c20510c
Revises: fd23493cdd64
Create Date: 2025-11-18 00:23:51.633864

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "722b8c20510c"
down_revision: Union[str, Sequence[str], None] = "fd23493cdd64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
