"""tags unique

Revision ID: e29ee2361b8d
Revises: 257e30585ca9
Create Date: 2025-11-13 23:10:56.168385

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e29ee2361b8d"
down_revision: Union[str, Sequence[str], None] = "257e30585ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag")
    op.drop_table("snippettaglink")
    op.drop_table("snippet")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snippet",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('snippet_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("favorite", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM("python", "javascript", "rust", "golang", name="language"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="snippet_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "snippettaglink",
        sa.Column("snippet_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["snippet_id"], ["snippet.id"], name=op.f("snippettaglink_snippet_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("snippettaglink_tag_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "snippet_id", "tag_id", name=op.f("snippettaglink_pkey")
        ),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("tag_pkey")),
    )
    # ### end Alembic commands ###
