"""orphan change

Revision ID: fd23493cdd64
Revises: bfdd0e067d2b
Create Date: 2025-11-17 23:50:41.822890

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd23493cdd64"
down_revision: Union[str, Sequence[str], None] = "bfdd0e067d2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_snippet_tag", "snippettaglink", ["snippet_id", "tag_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_snippet_tag", "snippettaglink", type_="unique")
    # ### end Alembic commands ###
